<%-- /admin/content/reports_content.jsp --%>
<%-- This file contains only the content specific to the Reports page --%>

<h2 class="mb-3 border-bottom pb-2 text-body"><i class="fas fa-file-alt"></i> View Reports</h2>

<a href="#" class="btn btn-primary mb-3 btn-add"><i class="fas fa-cogs"></i> Generate Report</a>
<%-- TODO: Link to a report generation page or trigger generation via AJAX --%>

<div class="table-responsive">
    <table class="table table-striped table-hover table-bordered align-middle">
        <thead class="table-light">
           <tr>
               <th>Report ID</th>
               <th>Report Type</th>
               <th>Generated Date</th>
               <th>Generated By</th>
               <th>Actions</th>
           </tr>
       </thead>
        <tbody>
             <tr>
                <td>1</td>
                <td>Monthly Sales Summary</td>
                <td>2025-04-01 08:00:00</td>
                <td>GiantREX</td>
                 <td>
                    <a href="#" class="btn btn-sm btn-success action-btn" title="View Details"><i class="fas fa-eye"></i></a>
                    <a href="#" class="btn btn-sm btn-danger action-btn" title="Delete" onclick="if(confirm('Are you sure?')){ showToast('Report deleted successfully.', 'success'); } return false;"><i class="fas fa-trash"></i></a>
                </td>
            </tr>
             <tr>
                <td>2</td>
                <td>User Activity Report</td>
                <td>2025-04-20 14:00:00</td>
                <td>staffREX</td>
                 <td>
                    <a href="#" class="btn btn-sm btn-success action-btn" title="View Details"><i class="fas fa-eye"></i></a>
                    <a href="#" class="btn btn-sm btn-danger action-btn" title="Delete" onclick="if(confirm('Are you sure?')){ showToast('Report deleted successfully.', 'success'); } return false;"><i class="fas fa-trash"></i></a>
                </td>
            </tr>
             </tbody>
    </table>
</div>
